max_width = 80
use_small_heuristics = "Max"
chain_width = 60
fn_single_line = true
hard_tabs = false
tab_spaces = 2
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition = "2021"
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = true
force_explicit_abi = true
normalize_comments = false
normalize_doc_attributes = true
wrap_comments = true
trailing_semicolon = true
trailing_comma = "Vertical"
